# -*- coding: utf-8 -*-
"""PC_PARCIAL 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdJbzMbBk2J5aRpoQWj6_-n38osKyOAr
"""

def factorial(n):#Calcula el factorial de un número entero n
    resultado = 1 #Inicializa una variable resultado a 1.
    for i in range(1, n + 1): #Utiliza un bucle for para iterar desde 1 hasta n.
        resultado *= i  # En cada iteración, multiplica resultado por el valor actual de i.
    return resultado #Devuelve el valor final de resultado.

# Uso de la función
numero = 5
print(f"El factorial de {numero} es: {factorial(numero)}")

def ordenamiento_burbuja(lista):#Define una función llamada ordenamiento_burbuja que toma una lista como entrada.
    n = len(lista)# Obtiene la longitud de la lista y la almacena en la variable n
    for i in range(n):#Este bucle externo itera n veces, donde n es la longitud de la lista. Cada iteración del bucle externo representa una pasada a través de la lista.
        for j in range(0, n-i-1):# Este bucle interno compara elementos adyacentes de la lista. En cada pasada del bucle externo, el rango del bucle interno se reduce en 1 ( n-i-1) porque los elementos más grandes se "burbujean" hacia el final de la lista.
            if lista[j] > lista[j+1]: # Compara el elemento actual lista[j] con el siguiente elemento lista[j+1].
                lista[j], lista[j+1] = lista[j+1], lista[j]  # Si el elemento actual es mayor que el siguiente elemento, los intercambia. Esta es la parte del "burbujeo" del algoritmo.
    return lista  #Después de que los bucles terminan, la función devuelve la lista ordenada. El return está fuera de los bucles para asegurar que se devuelva la lista completamente ordenada.
# Ejemplo de uso
mi_lista = [64, 34, 25, 12, 22, 11, 90]
lista_ordenada = ordenamiento_burbuja(mi_lista)
print("Lista ordenada:", lista_ordenada)

lista_desordenada = [64, 34, 25, 12, 22, 11, 90]# Se crea una lista llamada lista_desordenada que contiene una serie de números enteros en un orden aleatorio.
lista_ordenada = ordenamiento_burbuja(lista_desordenada)# Se llama a la función ordenamiento_burbuja (que ya explicamos en una respuesta anterior) y se le pasa lista_desordenada como argumento.
print("Lista ordenada: ", lista_ordenada) #Se imprime en la consola el mensaje "Lista ordenada: " seguido de la lista ordenada lista_ordenada.